language: java
jdk: openjdk11 
install: true
script: mvn clean install
cache:
        directories:
            - $HOME/.m2
sudo: false
#after_success:
#      - bash <(curl -s https://codecov.io/bash)
